import os 
from datasets import load_dataset, concatenate_datasets

if __name__ == '__main__':
    test_data1 = os.path.expanduser("~/data/CLEANED_OLD_tiger_test.jsonl")
    test_data2 = os.path.expanduser("~/data/CLEANED_OLD_tüba_test.jsonl")

    test_dataset1 = load_dataset("json", data_files=test_data1, split='train')
    test_dataset2 = load_dataset("json", data_files=test_data2, split='train')
    test_dataset2 = test_dataset2.rename_column("Treebank-Sentence", "Original sentence")
    test_dataset2 = test_dataset2.rename_column("Reconstructed-Sentence", "Canonical form")
    dataset = concatenate_datasets([test_dataset1, test_dataset2])

    fcr1 = test_dataset1.filter(lambda example: example["FCR"] == 1 or example["FCR"] == "1")
    gapping1 = test_dataset1.filter(lambda example: example["Gapping"] == 1 or example["Gapping"] == "1")
    bcr1 = test_dataset1.filter(lambda example: example["BCR"] == 1 or example["BCR"] == "1")
    sgf1 = test_dataset1.filter(lambda example: example["SGF"] == 1 or example["SGF"] == "1")
    noCCE1 = test_dataset1.filter(lambda example: (example["SGF"] == 0 or example["SGF"] == "0") and (example["BCR"] == 0 or example["BCR"] == "0") and (example["FCR"]== 0 or example["FCR"] == "0") and (example["Gapping"] == 0 or example["Gapping"] == "0"))

    fcr2 = test_dataset2.filter(lambda example: example["FCR"] == 1 or example["FCR"] == "1")
    gapping2 = test_dataset2.filter(lambda example: example["Gapping"] == 1 or example["Gapping"] == "1")
    bcr2 = test_dataset2.filter(lambda example: example["BCR"] == 1 or example["BCR"] == "1")
    sgf2 = test_dataset2.filter(lambda example: example["SGF"] == 1 or example["SGF"] == "1")
    noCCE2 = test_dataset2.filter(lambda example: (example["SGF"] == 0 or example["SGF"] == "0") and (example["BCR"] == 0 or example["BCR"] == "0") and (example["FCR"]== 0 or example["FCR"] == "0") and (example["Gapping"] == 0 or example["Gapping"] == "0"))

    fcr = dataset.filter(lambda example: example["FCR"] == 1 or example["FCR"] == "1")
    gapping = dataset.filter(lambda example: example["Gapping"] == 1 or example["Gapping"] == "1")
    bcr = dataset.filter(lambda example: example["BCR"] == 1 or example["BCR"] == "1")
    sgf = dataset.filter(lambda example: example["SGF"] == 1 or example["SGF"] == "1")

    noCCE = dataset.filter(lambda example: (example["SGF"] == 0 or example["SGF"] == "0") and (example["BCR"] == 0 or example["BCR"] == "0") and (example["FCR"]== 0 or example["FCR"] == "0") and (example["Gapping"] == 0 or example["Gapping"] == "0"))

    print("Hier ein paar Info's über die Testdaten: ")
    print("TIGER - Gesamt")
    print(test_dataset1)
    print("TIGER - FCR")   
    print(fcr1)
    print("TIGER - GAPPING") 
    print(gapping1)
    print("TIGER - BCR") 
    print(bcr1)
    print("TIGER - SGF")  
    print(sgf1)
    print("TIGER - NoCCE")  
    print(noCCE1)
    print("======================================== \n")
    print("TüBa - Gesamt")
    print(test_dataset2)
    print("TüBa - FCR")   
    print(fcr2)
    print("TüBa - GAPPING") 
    print(gapping2)
    print("TüBa - BCR") 
    print(bcr2)
    print("TüBa - SGF")  
    print(sgf2)
    print("TüBa - NoCCE")  
    print(noCCE2)
    print("======================================== \n")
    print("MERGED - Gesamt")
    print(dataset)
    print("MERGED - FCR")   
    print(fcr)
    print("MERGED - GAPPING") 
    print(gapping)
    print("MERGED - BCR") 
    print(bcr)
    print("MERGED - SGF")  
    print(sgf)
    print("MERGED - NoCCE")  
    print(noCCE)

    print("Creating a 50:50 Dataset now:")
    final_fcr = fcr1.select(range(111))
    final_gapping = gapping1.select(range(63))
    final_bcr = bcr1.select(range(12))
    final_sgf = sgf1.select(range(29))
    final_dataset = concatenate_datasets([final_fcr, final_gapping, final_bcr, final_sgf])

    print("======================================== \n")
    print("50:50 - Gesamt")
    print(final_dataset)
    print("50:50 - FCR")   
    print(final_fcr)
    print("50:50 - GAPPING") 
    print(final_gapping)
    print("50:50 - BCR") 
    print(final_bcr)
    print("50:50 - SGF")  
    print(final_sgf)
    print("50:50 - NoCCE")  
    #print(final_noCCE)